#----------------------------------------------------------------------------
#
# Set some installation folders.
#

# This is the directory structure used for installation.
IF(NOT DEFINED INSTALL_DIR_EXECUTABLES)
	SET(INSTALL_DIR_EXECUTABLES     "bin")
ENDIF(NOT DEFINED INSTALL_DIR_EXECUTABLES)

IF(NOT DEFINED INSTALL_DIR_LUA_MODULES)
	SET(INSTALL_DIR_LUA_MODULES     "lua_plugins")
ENDIF(NOT DEFINED INSTALL_DIR_LUA_MODULES)

IF(NOT DEFINED INSTALL_DIR_LUA_SCRIPTS)
	SET(INSTALL_DIR_LUA_SCRIPTS     "lua")
ENDIF(NOT DEFINED INSTALL_DIR_LUA_SCRIPTS)

IF(NOT DEFINED INSTALL_DIR_SHARED_OBJECTS)
	SET(INSTALL_DIR_SHARED_OBJECTS  "bin")
ENDIF(NOT DEFINED INSTALL_DIR_SHARED_OBJECTS)
