name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - # Ubuntu 18.04 x86
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_1804_x86:latest
          distribution-id: ubuntu
          distribution-version: "18.04"
          cpu-architecture: x86
        - # Ubuntu 18.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_1804_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "18.04"
          cpu-architecture: x86_64
        - # Ubuntu 18.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_1804_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "18.04"
          cpu-architecture: arm64
        - # Ubuntu 20.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: x86_64
        - # Ubuntu 20.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: x86_64
        - # Ubuntu 22.04 armhf
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: armhf
        - # Ubuntu 22.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 riscv64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: riscv64
    container: ${{ matrix.platform.image }}
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: ./build_artifact.py ${{ matrix.platform.distribution-id }} ${{ matrix.platform.distribution-version }} ${{ matrix.platform.cpu-architecture }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: build/repository
